name:                 a3
version:              1.0.0.0
visibility:           public
id:                   a3-1.0.0.0-inplace
key:                  a3-1.0.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:      APL.AST APL.Eval APL.Parser APL.Parser_Tests
import-dirs:
    /Users/nikolajkrarup/Documents/master/AP/APGit/Week3/a3-handout/dist-newstyle/build/aarch64-osx/ghc-9.8.4/a3-1.0.0.0/build

library-dirs:
    /Users/nikolajkrarup/Documents/master/AP/APGit/Week3/a3-handout/dist-newstyle/build/aarch64-osx/ghc-9.8.4/a3-1.0.0.0/build

library-dirs-static:
    /Users/nikolajkrarup/Documents/master/AP/APGit/Week3/a3-handout/dist-newstyle/build/aarch64-osx/ghc-9.8.4/a3-1.0.0.0/build

dynamic-library-dirs:
    /Users/nikolajkrarup/Documents/master/AP/APGit/Week3/a3-handout/dist-newstyle/build/aarch64-osx/ghc-9.8.4/a3-1.0.0.0/build

data-dir:
    /Users/nikolajkrarup/Documents/master/AP/APGit/Week3/a3-handout/.

hs-libraries:         HSa3-1.0.0.0-inplace
depends:
    base-4.19.2.0-1e06 mgprsc-9.7.0-5ab973ee tsty-1.5.3-30ed19e7
    tsty-hnt-0.10.2-f2156d19

haddock-interfaces:
    /Users/nikolajkrarup/Documents/master/AP/APGit/Week3/a3-handout/dist-newstyle/build/aarch64-osx/ghc-9.8.4/a3-1.0.0.0/doc/html/a3/a3.haddock

haddock-html:
    /Users/nikolajkrarup/Documents/master/AP/APGit/Week3/a3-handout/dist-newstyle/build/aarch64-osx/ghc-9.8.4/a3-1.0.0.0/doc/html/a3
