name:                 a5
version:              1.0.0.0
visibility:           public
id:                   a5-1.0.0.0-inplace
key:                  a5-1.0.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:      GenServer SPC SPC_Tests
import-dirs:
    /mnt/c/Users/simon/OneDrive/UNII/Ar_4/1.Semester/AP/Haskell/VoresOpgaver/AP/week5/a5-handout/dist-newstyle/build/x86_64-linux/ghc-9.6.7/a5-1.0.0.0/build

library-dirs:
    /mnt/c/Users/simon/OneDrive/UNII/Ar_4/1.Semester/AP/Haskell/VoresOpgaver/AP/week5/a5-handout/dist-newstyle/build/x86_64-linux/ghc-9.6.7/a5-1.0.0.0/build

library-dirs-static:
    /mnt/c/Users/simon/OneDrive/UNII/Ar_4/1.Semester/AP/Haskell/VoresOpgaver/AP/week5/a5-handout/dist-newstyle/build/x86_64-linux/ghc-9.6.7/a5-1.0.0.0/build

dynamic-library-dirs:
    /mnt/c/Users/simon/OneDrive/UNII/Ar_4/1.Semester/AP/Haskell/VoresOpgaver/AP/week5/a5-handout/dist-newstyle/build/x86_64-linux/ghc-9.6.7/a5-1.0.0.0/build

data-dir:
    /mnt/c/Users/simon/OneDrive/UNII/Ar_4/1.Semester/AP/Haskell/VoresOpgaver/AP/week5/a5-handout/.

hs-libraries:         HSa5-1.0.0.0-inplace
depends:
    base-4.18.3.0
    clock-0.8.4-a3cbb9d42c70d1935bf431495f9d5d7a34f80f2bfe18efc99085a90f3ece5cc5
    tasty-1.5.3-6c95fcbe221aaa43509d677521c7d1a61b01bcfa4804eb6e1c19fc9ec79e94ec
    tasty-hunit-0.10.2-c696f822497466b8d480aa6c30f33f808f9617e163389514a0e1aadec4ab930b

haddock-interfaces:
    /mnt/c/Users/simon/OneDrive/UNII/Ar_4/1.Semester/AP/Haskell/VoresOpgaver/AP/week5/a5-handout/dist-newstyle/build/x86_64-linux/ghc-9.6.7/a5-1.0.0.0/doc/html/a5/a5.haddock

haddock-html:
    /mnt/c/Users/simon/OneDrive/UNII/Ar_4/1.Semester/AP/Haskell/VoresOpgaver/AP/week5/a5-handout/dist-newstyle/build/x86_64-linux/ghc-9.6.7/a5-1.0.0.0/doc/html/a5
