name:                 a5
version:              1.0.0.0
visibility:           public
id:                   a5-1.0.0.0-inplace
key:                  a5-1.0.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:      GenServer SPC SPC_Tests
import-dirs:
    /Users/nikolajkrarup/Documents/master/AP/APGit/Week5/a5-handout/dist-newstyle/build/aarch64-osx/ghc-9.8.4/a5-1.0.0.0/build

library-dirs:
    /Users/nikolajkrarup/Documents/master/AP/APGit/Week5/a5-handout/dist-newstyle/build/aarch64-osx/ghc-9.8.4/a5-1.0.0.0/build

library-dirs-static:
    /Users/nikolajkrarup/Documents/master/AP/APGit/Week5/a5-handout/dist-newstyle/build/aarch64-osx/ghc-9.8.4/a5-1.0.0.0/build

dynamic-library-dirs:
    /Users/nikolajkrarup/Documents/master/AP/APGit/Week5/a5-handout/dist-newstyle/build/aarch64-osx/ghc-9.8.4/a5-1.0.0.0/build

data-dir:
    /Users/nikolajkrarup/Documents/master/AP/APGit/Week5/a5-handout/.

hs-libraries:         HSa5-1.0.0.0-inplace
depends:
    base-4.19.2.0-1e06 clck-0.8.4-cfac135b tsty-1.5.3-30ed19e7
    tsty-hnt-0.10.2-f2156d19

haddock-interfaces:
    /Users/nikolajkrarup/Documents/master/AP/APGit/Week5/a5-handout/dist-newstyle/build/aarch64-osx/ghc-9.8.4/a5-1.0.0.0/doc/html/a5/a5.haddock

haddock-html:
    /Users/nikolajkrarup/Documents/master/AP/APGit/Week5/a5-handout/dist-newstyle/build/aarch64-osx/ghc-9.8.4/a5-1.0.0.0/doc/html/a5
