name:                 a6
version:              1.0.0.0
visibility:           public
id:                   a6-1.0.0.0-inplace
key:                  a6-1.0.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:
    APL.AST APL.Check APL.Error APL.Eval APL.Parser APL.Tests

import-dirs:
    /mnt/c/Users/simon/OneDrive/UNII/Ar_4/1.Semester/AP/Haskell/VoresOpgaver/AP/Week6/a6-handout/dist-newstyle/build/x86_64-linux/ghc-9.6.7/a6-1.0.0.0/build

library-dirs:
    /mnt/c/Users/simon/OneDrive/UNII/Ar_4/1.Semester/AP/Haskell/VoresOpgaver/AP/Week6/a6-handout/dist-newstyle/build/x86_64-linux/ghc-9.6.7/a6-1.0.0.0/build

library-dirs-static:
    /mnt/c/Users/simon/OneDrive/UNII/Ar_4/1.Semester/AP/Haskell/VoresOpgaver/AP/Week6/a6-handout/dist-newstyle/build/x86_64-linux/ghc-9.6.7/a6-1.0.0.0/build

dynamic-library-dirs:
    /mnt/c/Users/simon/OneDrive/UNII/Ar_4/1.Semester/AP/Haskell/VoresOpgaver/AP/Week6/a6-handout/dist-newstyle/build/x86_64-linux/ghc-9.6.7/a6-1.0.0.0/build

data-dir:
    /mnt/c/Users/simon/OneDrive/UNII/Ar_4/1.Semester/AP/Haskell/VoresOpgaver/AP/Week6/a6-handout/.

hs-libraries:         HSa6-1.0.0.0-inplace
depends:
    QuickCheck-2.16.0.0-2a6bac89f6fc312aeaaedee693af99533643e23fcc104f13266aa234b5da221b
    base-4.18.3.0
    megaparsec-9.7.0-60f932a9022f946f3006952e73c99e7e20dd4e358789f962634f92d22391a027

haddock-interfaces:
    /mnt/c/Users/simon/OneDrive/UNII/Ar_4/1.Semester/AP/Haskell/VoresOpgaver/AP/Week6/a6-handout/dist-newstyle/build/x86_64-linux/ghc-9.6.7/a6-1.0.0.0/doc/html/a6/a6.haddock

haddock-html:
    /mnt/c/Users/simon/OneDrive/UNII/Ar_4/1.Semester/AP/Haskell/VoresOpgaver/AP/Week6/a6-handout/dist-newstyle/build/x86_64-linux/ghc-9.6.7/a6-1.0.0.0/doc/html/a6
